### ISSUE TITLE
how to use with docker

### ISSUE THREAD

**Issue by whatsadebugger** [bradleyjkemp/grpc-tools#110]
I tried setting an environment variable host.docker.internal:grpcdumpPORT in my docker compose file and the calls just appear as failed dialing host.docker.internal. Are there any examples of how to use with docker.

**Comment by bradleyjkemp** [comment]
Hey 👋 Could I get a few more details about your setup?

Is `grpc-dump` running outside the container and you're trying to log traffic from a client within the container?

**Comment by whatsadebugger** [comment]
yeah i have a few docker containers running using docker-compose. I was wondering how I could maybe see all the grpc calls one of them was making. grpc dump is outside the container and client is within the container yes.

**Comment by bradleyjkemp** [comment]
This guide should work for you then: https://docs.docker.com/network/proxy/

You can set up docker to use a given HTTP(S) proxy for a container. In this case you'll want to point it at the grpc-dump port.
