### ISSUE TITLE
ResourceExhausted on large payload

### ISSUE THREAD

**Issue by dparmar** [bradleyjkemp/grpc-tools#147]
I get the following error when proxying through grpc-dump.

`failed proxying s2c rpc error: code = ResourceExhausted desc = grpc: received message larger than max (13558592 vs. 4194304)`

It would be great to be able to override the default max message size (4 MB).

**Comment by bradleyjkemp** [comment]
Hey @dparmar this makes total sense. These tools don't really care about being denial-of-serviced so I've upped the max message size to 64MB (which easily fits your example)

Thanks for reporting!
