### ISSUE TITLE
proxy variable needs http:// prefix

### ISSUE THREAD

**Issue by nlohmann** [bradleyjkemp/grpc-tools#18]
I am following the example, but my application (using the gRPC C++ API on macOS) seems to only work if

```
http_proxy=http://127.0.0.1:12345
```

is passed rather than

```
HTTP_PROXY=127.0.0.1:12345
```

Only the lower-case writing of `http_proxy` and only with the `http://` prefix I can see output in grpc-dump (0.1.2).

**Comment by bradleyjkemp** [comment]
Hmm yes I got a report that Python requires the same format. The environment variable syntax is very loosely specified unfortunately so many applications require different formats.
Looks like the lower case and `http://` format is more common though. Let me check if that works with Go and I'll update the documentation/examples accordingly.

Thanks for the report!

**Comment by nlohmann** [comment]
You're welcome! I just found your project, and it could be really valuable for us!

**Comment by bradleyjkemp** [comment]
Yup seems Go is quite lax with what formats it accepts for these environment variables.
I've updated the documentation and tests to use the more widely accepted format of `http_proxy=http://...` (efdf360978281808a7d8a0308463ed63a5bda400)
