### ISSUE TITLE
error: Decompressor is not installed for grpc-encoding "gzip"

### ISSUE THREAD

**Issue by nlohmann** [bradleyjkemp/grpc-tools#19]
For compressed gRPC messages, I get the following error in grpc-dump (0.1.2, macOS):

```
"error":{"code":12,"message":"grpc: Decompressor is not installed for grpc-encoding \"gzip\""}
```

The request seems not to be forwarded to the server.

I installed grpc-dump via homebrew. Is there anything I can do to use compression?

**Comment by bradleyjkemp** [comment]
Interesting, I've not used gRPC compression before but it looks like this will be simple to add. At the moment I don't think there's a way for you to use compression without me making a new release with support.

In your setup do you know if the server also supports uncompressed requests? I'll try and make it so that the request to the server uses the same encoding/compression but that might take a bit more refactoring than just terminating compression at the proxy.

**Comment by nlohmann** [comment]
I do not need to install via Homebrew - I could also compile from source. I am just no Go expert, so I cannot add compression support myself.

I need to check whether I can switch off compression support for the server. I tried to switch it off at the client via the client context, but compression seems to be used anyway.

**Comment by bradleyjkemp** [comment]
@nlohmann I've replicated your issue using curl and the small patch in PR #20 seems to enable support for gzip (certainly the "Decompressor is not installed" error is no longer returned).
I haven't been able to test this end to end yet but would you be able to build this and see if this now works for you?

**Comment by nlohmann** [comment]
Thanks for the effort. Unfortunately, my Go skills are even worse than I thought. I do not know how to build binaries from the branch. I tried

```sh
env GO111MODULE=on go get github.com/bradleyjkemp/grpc-tools@gzip-compression
```

, but did not find binaries anywhere.

And

```sh
go run grpc-dump/main.go 
```

yields an error:

```
# command-line-arguments
grpc-dump/main.go:52:30: undefined: dumpInterceptor
```

Sorry for being such a Go noob...

**Comment by bradleyjkemp** [comment]
Haha no worries, Go has the (unintuitive at first) behaviour that if you specify a specific file then it ignores all other files in that package. If you've already got the branch checked out then just `go run ./grpc-dump` should work. You can also take a look at `integration_test/test.sh` to see how that builds the binaries locally.
If you can't get this working either just let me know and I'll post some pre-release binaries with this patch :slightly_smiling_face:

**Comment by nlohmann** [comment]
I tried and I can confirm it works now! Thanks for the quick help!

**Comment by bradleyjkemp** [comment]
👋 For some reason this issue is the most viewed page on this repo.

If you're reading this, I'd be really interested how you ended up here? Are people still seeing this error?

**Comment by charlescrain** [comment]
@bradleyjkemp I ended up here because I used a grpc client that defaulted to using gzip  when my server wasn't using any compression.

 For anyone who finds there way here, make sure to check that your client and server matches the compression used by your client
