### ISSUE TITLE
Add timestamps to messages

### ISSUE THREAD

**Issue by nlohmann** [bradleyjkemp/grpc-tools#22]
It would be great if `grpc-dump` would add timestamps of the time it records messages. This would not only allow to postprocess the output and make timing analyses, but also maybe to use the timestamps to mimic the (relative) timing behavior in `grpc-replay`.

**Comment by bradleyjkemp** [comment]
Closing this as a duplicate of #9 but these are excellent use cases so I'll take this ticket as a strong vote to work on #9 at the next opportunity I get 🙂 

Do you have any strong preferences on timestamp format? By default, Go is going to marshal timestamps as RFC 3339 strings which seems standard enough that it's going to be easily parseable by most languages

**Comment by nlohmann** [comment]
Oh, sorry no have missed that. ISO 8601 would be great, and RFC 3339 seems to be just that.
