### ISSUE TITLE
Metadata sent from Server->Client is not handled

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/grpc-tools#43]
gRPC metadata is dumped when sent in the request from Client->Server but Server->Client metadata is not handled (https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#receiving-metadata).

I'm also unsure if this is handled correctly by grpc-proxy. It appears to be on quick inspection but there's no test coverage so it's hard to say for sure.

**Comment by swuecho** [comment]
I discover similar issues recently. If error instead of correct response is returned from server, grpc-dump will not pass the the error to the client.

**Comment by bradleyjkemp** [comment]
@swuecho Ah interesting, yes I can reproduce this. I thought this used to work so I'll look at fixing this and adding a regression test ASAP!

**Comment by bradleyjkemp** [comment]
@swuecho and that should now be fixed as of v2.0.1 (or pr #45), thanks for reporting this! 🙂 

(I'll leave this issue open because Server->Client metadata support is still missing)
