### ISSUE TITLE
Support comments in JSON dump format

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/grpc-tools#7]
For dumps written or edited by hand (e.g. those used with grpc-fixture or grpc-replay) it would be nice to support comments in the JSON dump so that users can document their dumps.

These still need to support streaming decoding so running the entire file through a JSON pre-processor is not an option.

**Comment by nlohmann** [comment]
Just my two cents (and I may be biased through my work at [nlohmann/json](https://github.com/nlohmann/json): Please don't add comments to a JSON format. JSON does not support comments. If you do want to have a format that supports types like JSON *and* comments, I'd propose to go for YAML. But the moment you have a file with a `.json` that contains comments, you're mostly out of luck processing it in any other JSON compliant tool.

**Comment by bradleyjkemp** [comment]
So my background on this comes mainly from JSON as configuration where I've found it very useful to be able to document why a certain option is enabled or what a specific value means. This point is perhaps not relevant for these tools because the output is definitely data rather than configuration.

I agree `grpc-dump` should definitely only produce valid JSON but for things that process the dump format (e.g. `grpc-fixture`/`grpc-replay`) I can see some benefits in being flexible in what they accept.

However, I've been reading through your responses to similar requests on https://github.com/nlohmann/json and think I'm convinced this isn't something that should be supported. (in particular https://tools.ietf.org/html/draft-thomson-postel-was-wrong-02 was something I hadn't seen before).
So I'm happy to close this as something that users should solve themselves (e.g. via a cli that strips comments).
