### ISSUE TITLE
Listen to different interfaces capability

### ISSUE THREAD

**Issue by BastienFaure** [bradleyjkemp/grpc-tools#79]
Hello !

I would like the grpc-dump tool to give the ability for users to make the proxy listening on a different interface or IP address.

I found my way by monkey patching the source code and it worked pretty well, guessing you would implement this easily by just adding a CLI argument and reinjecting the value into the right function call :)

Thanks !

**Comment by bradleyjkemp** [comment]
Hey @BastienFaure, yes that'll be an easy option to add as a CLI flag.

Just out of interest, what's your use case for this? You want to restrict grpc-dump to only listen on one interface rather than all?

**Comment by BastienFaure** [comment]
Hi @bradleyjkemp !
So my use case is very simple, I'm running an app in a virtual machine and I can't reach the proxy from that source. Of course I could have circumvented the limitation by doing port forwarding/tunneling or whatever but I guess that would be useful in other cases :)

Thanks mate

**Comment by bradleyjkemp** [comment]
This is all done 🙌  You should be able to update to v0.2.5 and use the `--interface` flag to listen on whichever interface you need (e.g. --interface 0.0.0.0 to listen on all interfaces)
