### ISSUE TITLE
Include a timestamp for each gRPC message

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/grpc-tools#9]
Each server/client message should have a timestamp logged of when it was received.
This will give users greater debugging power because e.g. they'll be able to find requests that took a long time.

This should be an easy addition to `grpc-dump/recorded_server_stream.go`

**Comment by bradleyjkemp** [comment]
@nlohmann this should now work if you build from master 🎉

**Comment by nlohmann** [comment]
I can confirm that it's working! Very nice! Thanks for the quick response! I'll be traveling this week, but next week I'll give it a try at work.
